### ISSUE TITLE
`node.matches` doesn't work

### ISSUE THREAD

**Issue by ximex** [jonashellmann/skip-netflix-intro#3]
This works:
```js
node.querySelector("button.watch-video--skip-content-button")?.firstChild.click();
```

**Comment by jonashellmann** [comment]
Thank you for your comment, I'll try to look into this issue tomorrow. In the Firefox browser, however, the current version works for me.

**Comment by jonashellmann** [comment]
I just confirmed that your suggested code change works fine.
Therefore I created a new version and uploaded it to the Mozilla addon store. Version 1.3 should be available now. I hope it works for you then.
Again, thanks for letting me know about this issue!

**Comment by ximex** [comment]
thx. first test works
